### ISSUE TITLE
Scan is not being started

### ISSUE THREAD

**Issue by cwaazywabbit** [sethsec/celerystalk#111] opened 2019-08-05 06:42 UTC
So on a fresh, up-to-date install, celerystalk doesn't start with the test.

```
./celerystalk workspace create -w client -o /root/client -m vapt
./celerystalk scan -u http://saas.client.com/test
./celerystalk query watch
```
![image](https://user-images.githubusercontent.com/6714156/62444035-b7cc3b00-b75c-11e9-981f-b4b5fa421c69.png)

pause/resume all doesn't do anything. Using `./celerystalk query watch` I notice no task was moved to "Paused" when running `./celerystalk pause all`

![image](https://user-images.githubusercontent.com/6714156/62444125-f235d800-b75c-11e9-96fe-b47eae896285.png)

**Comment by sethsec** [comment] 2019-08-06 13:54
Thanks for the heads up.  It still works on my test boxes, but on a clean install i got the same thing. It is redis related. I was able to add `port 6379` to the bottom of /etc/redis/redis.conf and restart redis-server to fix it, but i'm not sure about the root cause yet. I'll track it down.

**Comment by cwaazywabbit** [comment] 2019-08-18 15:18
Fixed this by running the following commands in the same order:

```
pip2 install celery==4.2.2
pip2 install -r setup/requirements.txt --upgrade
```

I think it's wise to use `pip2` instead of `pip` in _setup/install.sh_ while _celerystalk_ is based on Python 2.x

**Comment by sethsec** [comment] 2020-01-26 03:57
This should be fixed now. Seems to work with just the pip2 fix. If you think pinning celery to 4.2.2 is still needed, please let me know.

**Closed by sethsec** 2020-01-26 03:57 UTC
